---
name: Unit tests
on:
  push:
    paths-ignore:
      - '**/*.md'
      - '**/*.asciidoc'
      - '**/*.txt'
      - 'docs/**'
      - '.ci/**'
      - '.buildkite/**'
      - 'scripts/**'
      - 'catalog-info.yaml'
  pull_request:
    paths-ignore:
      - '**/*.md'
      - '**/*.asciidoc'
      - '**/*.txt'
      - 'docs/**'
      - '.ci/**'
      - '.buildkite/**'
      - 'scripts/**'
      - 'catalog-info.yaml'

jobs:
  test:
    name: Test
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        node-version: [16.x, 18.x, 20.x]
        os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install
        run: |
          npm install

      - name: Lint
        run: |
          npm run lint

      - name: Unit test
        run: |
          npm run test:unit

  license:
    name: License check
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install
        run: |
          npm install

      - name: License checker
        run: |
          # TODO: remove excludePrivatePackages after this goes live
          npm run license-checker -- --excludePrivatePackages
